<?php
$pageTitle = 'Mad Kenpo Scientist pt. 1';
include 'header.php';
?>

<!--BEGIN CONTENT-->


			<TABLE WIDTH="100%" HEIGHT="100%" BORDER="0" CELLPADDING="3" CELLSPACING="5">
<!--PAGE NAME-->
				<TR><TD HEIGHT="25" BGCOLOR="#890C08" CLASS="BODY"><a name="top"></a>
				<a href="/web/20111229184702/http://www.martialscienceuniversity.com/" class="h1">
				<div>Excerpts from the Diary of a &quot;Mad&quot; Kenpo Scientist, Part One<br><br></div></a></TD></TR>

<!--JUMP MENU-->
				<TR><TD BGCOLOR="#CCCCCC" class="BODY" VALIGN="TOP">
					<a href="/web/20111229184702/http://www.martialscienceuniversity.com/" class="art">
<h1 align="center" class="art">Historical perspective</h1></a>
  <p align="center"><strong>By Ron Chap&eacute;l, Ph.D.</strong><br>
  (Published in Combat Martial Sports Nov. 01 issue)</p>
<p align="right"><br>
  <a href="/web/20111229184702/http://www.martialscienceuniversity.com/articles/"><font size="1">Return to Article Archive</font></a></p>
<p align="justify">&nbsp;</p>
<p align="justify">It has been arguably stated, “Ed Parker is the father of American Karate.” Although there are some who may take issue with such a claim, there are particulars that are undeniable and those who subscribe to Ed Parker’s lofty status in martial arts history are probably much closer to the truth than they know. It is a given Ed Parker was the first to bring and create an American Concept of the Asian fighting arts to mainland America. Although pre-dated by others who essentially transplanted Asian Arts with cultural accouterments intact, it is clear Ed Parker was the first to approach the arts from an American point of view. From an American historical perspective, this makes him a pioneer of quite significant proportions. </p>
<p align="justify"> 
Historically, the art as it existed in China, was an immense body of knowledge encompassing a wide variety of physical sciences. All-inclusive in concept, it included, weapons warfare, self-defense, exercise therapy, entertainment, religion, herbal therapy, and other forms of medicinal healing.  In actuality, it was more of a broad range of various disciplines and sciences interconnected by, and related to the human body. This is extremely important. Because this science crosses so many diverse academic concepts and scientific boundaries, it makes its study even by the educated and scholarly difficult. Also for this reason as well as its destructive component, the sciences were and still are in the hands of relatively speaking, a small group of people. Clearly the art of China is the “mother” of all arts. (The “father” is perhaps for another article) </p>
<p align="justify"> 
As the sciences migrated from within the borders of China to other nations, its name was translated from the original Chinese, to simply those meaning ‘”kempo or kenpo.” However with this interpretation and the inability or unwillingness to take on such a vast body of work, Kenpo slipped away from its “martial science” heritage and took on a significantly different meaning. Once transplanted, it became an interpretive, culture based, nationalized, “martial art.” No longer a science but now a subjective art form, each country instead chose to focus on and interpret specific slices of the very large “Chinese pie.” This is very evident in the Korean, Okinawan, and Japanese national arts. Other countries like India and Pakistan as well, although staying closer to the science roots, chose to also infuse a very heavy cultural and religious aspect to their interpretations. After portions of the Chinese Sciences were adapted to the individual cultures and became a “martial art,” then the second stage of development was not far behind. Before we move on an important reminder. When the science left China it became an art form. </p>
<p align="justify"> 
The second stage and more migration brought another significant transformation as well. Now it began to gradually evolve from a “martial art,” to a “martial discipline.” The next evolutionary step would eventually take it to the lowest common denominator. This is “martial sport.” As an example, Korean cultural developments spawned Tang Soo Do. This is the only Korean art that pays homage to its Chinese roots through its name. This art was distilled ultimately into the national sport/discipline Tae-kwon-do. The Okinawan’s moved from the art they called “te” (or hand), to exporting the heavily "cuturalized" creation the Japanese called Karate-do. Here, it was designed to be a companion sport/discipline to Judo. Other singular elements of the Chinese Science influenced the creation of jiu-jitsu prior to Karate-do in Japan. Then of course, jiu-jitsu was distilled down to the sport of judo. In some instances, like with the Japanese, the idea of actual fighting was only used as a base for the “art form,” with self-enlightenment and personal discipline being the primary goal. This process caused the creation of arts like Aikido. The cultural mindset felt this could be best accomplished through a nationalistic physical activity. So you see, the historical groundwork for the many different Ed Parker creations were clearly in place. </p>
<p align="justify"> 
My point here is a simple one. Learning the collective Chinese Sciences is not only difficult, but also very time consuming. It is properly structured so you have to learn from someone else, who can bring all of these sciences together for you in layers of educational lessons. Even the very well educated would have great difficulty because of its diverse nature. That is why the tradition of passing it from one to another is so important. Because of this, extremely abbreviated focused versions were created for larger national consumption. From there they ultimately evolved into sports. The Ed Parker creation, “Kenpo-Karate” is a product of that process as well.</p>
<p align="justify">
Originally when Ed Parker came to the mainland, he taught what he called “Chinese Kenpo,” to emphasize its true origin. Some like Master Steve Herring in Pasadena, California, still teach from this original perspective. In fact, Ed Parker even had a Tai Chi master teaching with, and for him in his school in Pasadena. Having himself studied with the notable Chinese Grandmaster, Ark Wong, as well as other masters from Northern California, Ed Parker began expanding on the martial education he received in Hawaii from his only Kempo (Kenpo) instructor, “William” Kwai Sun Chow. Self named “Thunderbolt” for his speed and hard-hitting approach; this is the man that planted the seed of practicality in what was to become the very large Ed Parker Garden.</p>
<p align="justify">  
Wanting to spread his creation, Ed Parker was faced with the same dilemma as those before him. Not only was he learning the sciences himself, but also this necessitated a constant expanding and evolving of his art. Additionally, its complexity was such that teaching also required a definite “hands on” approach. This, coupled with the extreme destructive potential of the information entrusted to him by the Chinese, forced him to make a conscious decision to do what had been done so many times before. He stripped away much of the real Chinese Science in favor of a physically conceptual vehicle.</p>
<p align="justify">  
Borrowing from history, he created what could be called ”American Karate.” Sort of a “Kenpo-do or “way” art. The emphasis however, was not on the “way” you performed its movements, but the “way” you approach your training. He also, unlike Japanese Karate-do, shifted the emphasis from the “way” you do it, to a “results” driven perspective. This, he felt the American public demanded. He also realized the American Culture in general, would not be conducive to spend many years training without results they could see very quickly. Thus he needed a way to “sale” Kenpo on a large scale with rather quick results. He soon decided “Kenpo-Karate” was going to be that vehicle. So it is important we realize, “Kenpo-Karate” is a component of, and only a small part of Ed Parker’s American Kenpo. This is just like the way other “arts and sports” are only a small part of the Chinese Science. The “Old Man” (as he was affectionately called by most of his senior students,) had a lot more up his sleeve than “Kenpo-Karate.”</p>
<p align="justify">  
The process took a different turn when he discovered something he termed “reverse motion.” While viewing himself on film running in reverse, he discovered many aspects of useable motion he had never considered before. This not only expanded his physical vocabulary, but gave him the perfect vehicle to teach a “motion based interpretive art.” This was a component art that emphasizes continued movement to overwhelm an opponent while focusing on soft tissue strikes. This is why he often privately referred to it as “Motion-Kenpo.” He also had a private joke he used to describe other disciplines. He called them “partial arts.” He also acknowledged his own “Kenpo-Karate” was also a “partial art” but, “It works!” Practitioners, who are honest, will find it difficult to give an articulate explanation of this component of the much larger American Kenpo, without using the word “motion.” Further reflection will also cause the intelligent to acknowledge “Kenpo-Karate” although somewhat effective, is missing a great deal. Now attaching the Japanese word “karate” once again for public familiarity, he was then ready to sale his “Kenpo Karate” to the world. Later on, he regretted using the term “karate,” but he felt he was “stuck” with it for a variety of reasons.</p>
<p align="justify"> 
This method enabled him to spread Kenpo-Karate all over the world, and teach concepts and interpretive “motion” as opposed to hard specific information. It was not necessary for him to see a student regularly. The material “worked,” and the extreme mayhem from its execution would have to be the responsibility and borne by the individual. He never said “put your fingers in someone’s eyes.” He only said it was possible if you feel the necessity. This is also why you can’t find a consensus on technique execution in “Kenpo-Karate.” By design, it is interpretive and in that sense, a true martial art. However, the only thing that matters in self-defense is that it works for the individual when they need it.</p>
<p align="justify">
This method of spreading his art was made possible for one simple reason. The majority of Ed Parker’s black belts at the time were already advanced students in other arts, and brought basic skills from their disciplines with them. They became Ed Parker converts to his logic and reasoning approach. Even though many of their basics were different from what he wanted to teach, they all had some measure of functional skill as a base. For the most part, these guys were old school “street fighters” anyway. This meant they could take care of themselves on the street, and that is what “Kenpo-Karate” was supposed to be about. This diversity in basics has been played out in students ever since. Ed Parker never really taught strict basics to the majority of his students. He taught “basic concepts.” He taught what a particular maneuver was supposed to accomplish, and gave you ideas of how to make it functional, much like the rest of his teaching. This is something that didn’t exist in the traditional arts. Add to the mix students were given flexibility in thought and action, and students from all styles and disciplines signed on for a ride on the fast moving “Ed Parker Express.” </p>
<p align="right"><span class="top"><a href="/web/20111229184702/http://www.martialscienceuniversity.com/articles/">Return to Article Archive</a></span></p>
				</TD></TR>
				
<?php include 'footer.php' ?>