<?php
$pageTitle = 'Mad Kenpo Scientist Pt. 3';
include 'header.php';
?>
<!--BEGIN CONTENT-->


			<TABLE WIDTH="100%" HEIGHT="100%" BORDER="0" CELLPADDING="3" CELLSPACING="5">
<!--PAGE NAME-->
				<TR><TD HEIGHT="25" BGCOLOR="#890C08" CLASS="BODY"><a name="top"></a>
				<a href="/web/20111006004459/http://www.martialscienceuniversity.com/" class="h1">
				<div>Excerpts from the Diary of a &quot;Mad&quot; Kenpo Scientist, Part Three<br><br></div></a></TD></TR>

<!--JUMP MENU-->
				<TR><TD BGCOLOR="#CCCCCC" class="BODY" VALIGN="TOP">
					<a href="/web/20111006004459/http://www.martialscienceuniversity.com/" class="art">
<h1 align="center" class="art">SubLevel Four Kenpo Concepts</h1></a>
  <p align="center"><strong>By Ron Chap&eacute;l, Ph.D.</strong><br>
  (Published in Martial Sport Magazine Mar. 03)</p>
<p align="right"><br>
  <a href="/web/20111006004459/http://www.martialscienceuniversity.com/articles/"><font size="1">Return to Article Archive</font></a></p>
<p align="justify">&nbsp;</p>
<p align="justify">Up until the passing of Ed Parker I had not given much thought to the diversity of Ed Parker’s teachings over the years, and its affect on what he, in general called “American Kenpo.”  I considered myself a good friend first and a student second, and I assumed his contemporary lessons for me were no different than others he considered “close.” I watched him teach and influence a variety of motion Kenpo- Karate based concepts over the years. He continued to share with former students who had gone on their own, as well as his current black belts who taught commercially. However I really thought there were others he was teaching similarly to myself and never gave it much thought. In all fairness, who really knows? </p>
<p align="justify">
  
After his passing I was caught off guard at the amount of curiosity students at all levels of Kenpo had about where my information came from. I took for granted and spoke of things they had never heard of from an American Kenpo perspective. I was further surprised how strongly some argued that such things “didn’t exist in Ed Parker’s system” and how their personal understanding of his creation was “complete.” Others simply assumed his Infinite Insight series of books were the collective sum of his knowledge. “How arrogant,” I thought to myself for someone to assume they know all Ed Parker knew, or the sum of his knowledge was in a few books on concepts. Others wanted to know where this information was written down. Still others asked the question, “Why didn’t Ed Parker teach me that?” That’s a question they should probably reserve for themselves. </p>
<p align="justify">
  
Clearly there are advanced aspects to Mr. Parker’s commercial vehicle he often privately called Motion-Kenpo. However I personally use the word “advanced” to mean knowledge not contained therein, not to demean or as a put down of other concepts. I coined the terms Advanced American Kenpo Concepts, and SubLevel Four based on phrases Ed Parker always used when he wanted to work on very specific areas in my interaction with him. He borrowed the former and used it himself on the jackets of the videos his son produced. </p>
<p align="justify">                      
This advanced level of Kenpo, shortened sometimes to SL-4™ tends to be misunderstood because it covers multiple areas of applications. When SubLevel Four is used to strike, nerves are activated through Destructive Sequencing utilizing Chinese Acupuncture Meridians and nerves embedded in cavities. This causes the subject to involuntarily react in a predictable manner and creates a Negative Body Posture. This places him at an anatomical disadvantage. In simple terms, nerve cavities are made accessible and body positioning is mechanically restricted and vulnerable, thus the term Negative Body Posture. </p>
<p align="justify"> 
This unique methodology effectively manipulates his body for each additional action until he is essentially incapacitated by a bodily dysfunction called Physical/Mental Disassociation, or actual and complete unconsciousness. At the very least your adversary is severely momentarily physically restricted. During this striking process, minor or major manipulations are employed to assist in placing the opponent into a negative posture to facilitate the desired nerve cavities being “open” and accessible. Once that occurs, particular natural weapons are then executed in a specific method, manner, angle, and known sequence in conjunction with the created negative posture. This process is initiated by your opponent’s own aggressive actions and posture. When you are capable of understanding as well as reading Martial Posture, you know what nerves are most easily accessed based on his actions.  
Although it would seem to be a complicated process, with proper basic training it really is not. Freshman students routinely do it quite effectively. The method is all in the design of the Default Techniques and the level of knowledge in their execution. If you learn the technique properly, it functions on its own. Like with an automobile, when you turn the ignition key, a series of very complex things take place in successive order. You don’t really have to know how or why these things happen to be a driver, you just have to know how to turn the key.  </p>
<p align="justify">
There are four physical levels of curriculum in SubLevel Four. At the first level students learn the Default Technique for each assault or attack scenario. The design of the technique allows a student to express their basic skills and perfect applications indefinitely. Each technique has a particular method and manner of execution that is, unlike Motion-Kenpo, not flexible. This is because basic body structure and the cultivation of newly formed synaptic pathways are being developed, as well as being “hard wired” under stress. This is a process that most traditional arts attempt to do in some manner or another. Motion-Kenpo’s approach is an exception to that process, not the rule. There is a reason why everyone moves the same in more traditional arts like Wing Chun, or in Taiji forms, as well as in American Kenpo’s parent, Chaun-fa.</p>
<p align="justify">  
Each technique is also an expression of basic skills that can be performed without a partner. When properly executed they are essentially a functional mini-form or set. They can develop internal energy by forcing correct body mechanics, breathing, and Body Aligning Resistance similar to Tai Chi. Each Default Technique has many levels of applications and lessons built into their design that go far beyond what is obviously seen. To the unknowledgeable, they look essentially the same.</p>
<p align="justify">  
The first level, (which contains 10 courses white to black) also insures the techniques are absolutely anatomically and mechanically functional. Grabs must be defended properly and not as attempted grabs. There are no “throw away” techniques. This insures students can use the curriculum functionally if not yet precisely and defend themselves rather quickly. The higher a student moves in course level the more skilled he becomes, and the better he executes previous course curriculum that is constantly revisited.  This was a major source of discourse among Parker followers. Once they had “learned” something, they wanted to move on. Ed Parker constantly re-examined everything. Current students in SL-4 are responsible for their present course of study as well as all courses previously studied, and subsequent improvements.  Although everyone does the same thing, it is clear more advanced students do it better with more precision and power.  </p>
<p align="justify">
The second level explores the true application of forms and set and integrates that functionality into the current level of instruction. When viewed from a non-motion perspective, there is a great deal of information there.  Additionally, each assault scenario is re-visited with the additional responsibility of an escalation of the attack beyond the default scenario. Here we emphasize counter grappling through mechanisms learned but not emphasized at level one that create a Grapple Control Mechanism or “G.C.M.” Also other considerations are added. The Default Technique moves upward in aggression. As an example, in a technique like “Sword and Hammer,” they are obliged to defend against an additional punch with the shoulder grab. This is taught without venturing outside of already created synaptic pathways or muscle memory. There are no singular assault scenarios at this stage. A punch is never “just one punch.” A grab is always a precursor to further assaults in the Level Two Default Technique sequence.  
Level Three is a very significant level because the accumulated skill developed here should be such that completing a Default Technique Sequence in its entirety should not be the student’s goal. Instead the first one, two, or three moves of the Default Technique should be executed at such a high degree of skill, that it renders the rest of the technique sequence unnecessary. Although still available if needed, this allows a built in safety net at all levels of performance and in situations from beginner to advanced.</p>
<p align="justify">  
Level Four is arguably the most physically challenging and certainly the most difficult. This is the component that is the most recognizable as different from conventional Kenpo. Although as you move through the other three levels you are being slowly introduced to Level Four Concepts, it is not until you get to this level that you are responsible to execute full Control Manipulation off of the same external stimulus of previous curriculum.</p>
<p align="justify">  
SubLevel Four Control Manipulations have often been confused with jiu-jitsu, but its parameters are much different and are not pain reliant as other manipulation arts. This makes the manipulations different from conventional Jiu-jitsu, and Aikido, execution. Its roots are in a component of all Chinese Arts called Chin-na. However Mr. Parker dictated very specific “American Kenpo Parameters” different form even Chin-na. This component is integrated with the nerve striking sciences. SubLevel Four Control Manipulations can be every bit as aggressive as the stand-alone striking component. They are engineered to produce skills that work together or independently of each other as you desire, or as the situation dictates. By definition Control Manipulation is not a part of Motion-Kenpo, and is not included in the 4 ranges of combat as found in Ed Parker’s “Encyclopedia of Kenpo.”  
Additionally a very important component called “Psychology of Confrontation” is taught in some form at all levels. It is very important to get into the mind of the attacker and understand his actions relative to the assault. Once you understand what he is trying to accomplish you are better equipped to see that he not successful in his goal. This is also where the stress component is increased in intensity. The method is similar to military training or civilian law enforcement role-playing scenarios. This is where your training becomes really “hard wired” into muscle memory. </p>
<p align="justify"> 
Although the learning process never stops, self-exploration isn’t a part of that process. A student must have a significant foundation of knowledge not conceptually available except by being taught. Information is examined under the tutelage of competent and knowledgeable instructors only. The lowest level of commitment acceptable is level one. Students with commitment levels lower than level one and who have not accepted the commitment necessary for study are therefore not accepted into the student body. We are absolutely results driven and are not obliged to accept everyone. Our younger students are very serious and our approach is not recreational. This is part of our responsibility to the student to not instill false confidence through rank that could get them seriously injured. Integrity comes from excellence, and excellence comes from integrity.</p>
<p align="justify">  
Proper (as opposed to aesthetically) Anatomical Alignment is also stressed continually, and is paramount at all levels to create structural integrity and internal energy flow. The creation of structural integrity is a science unto itself. Should the body not be placed in the proper position, effectiveness is diminished significantly offensive and defensively. Without the knowledge of Anatomical Body Positioning, none of these will work. What the Chinese call “Chi” or internal energy cannot be generated without proper body mechanics. Conversely, proper body mechanics cannot exist without “chi” being generated. Therefore these two elements, once initiated by proper physical movement and body mechanics, feed off of each other insuring the existence of the whole. You cannot achieve one without the other. Like a spiraling staircase, if you continue to feed the mechanics, the internal grows which in turn feeds back into the mechanics. It is one of many processes in SubLevel Four Kenpo and is very real, and quite effective.  
So you see, SubLevel Four Kenpo in addition to everything else is a “process.” It is a very unique method and manner of study and training of specific Kenpo curriculum. There are no “what ifs” or short cuts. It is the execution of a curriculum specifically designed to get a student to the highest level of skill and knowledge his/her personal commitment will allow. The process is indefinite and instruction never stops. The lowest level of commitment acceptable is level one where everyone must start. Some feel they should begin at a higher level, because they have studied Motion-Kenpo. The motion concept is so diametrically opposed to SL-4 it is not possible. Although previous experiences are an asset, previous lessons for the most part are not.</p>
<p align="justify">  
When you move to “hard” non-flexible curriculum, you may no longer think of “motion” as the dominant theme. SubLevel Four diminishes “tailoring” significantly, and negates the Alphabetical and Numerical Rearrangement Concepts, along with a great deal of other Motion-Kenpo ideas and rules.  “Motion” is still there, and so is “tailoring” but they become restricted to much smaller parameters for effectiveness of the dominant sciences. How and why you move takes on different characteristics. Tailoring is usually restricted to Geometry Limitations inherent in the diversity of human anatomy. That is, if a person is too tall for you to reach the prescribed target, there is a tailored adjustment made, but the target change usually conforms to the same meridian for destructive effect, not personal preference. Motion-Kenpo Karate is 90% “Tailoring,” SubLevel Four is the opposite with a 90% structured curriculum. Your body has effective limitations. Remember, our priority is supposed to be self-defense, not as Ed Parker stated, “Useless motion.”</p>
<p align="justify">  
We tend to forget that although Chinese-Kenpo is ancient, the whole of American Kenpo’s interpretation is a relatively recent development. With the inclusion of Chinese-Kenpo and Kenpo-Karate as the forerunner components of what is generally practiced today, it’s still only about thirty years old. Take away Chinese-Kenpo and it is considerably younger, but draws from ancient sciences that have been proven. The difficulty was to put them into an efficient modern cultural context with a reasonably efficient time learning curve.</p>
<p align="justify">  
Our one and only Senior Grandmaster was not yet sixty years old when he passed away. In Chinese terms, he would be considered just beginning to move into his prime. Most of the subsequent self-proclaimed “Grandmasters” of his commercial art got there faster than he did. Yet Ed Parker was a perpetual student and was still learning until the day he moved on. Mr. Parker was a genius, and he definitely accelerated the learning process from the Traditional Chinese. He was always exploring and accumulating more knowledge and never failed to remind students, “One doesn’t become great until they realize what they know is very little.” What some call evolution, Ed Parker called “tailoring and rearrangement.” They are doing what Ed Parker always taught for Motion-Kenpo. For this they should be commended. </p>
<p align="justify"> 
However, this has given us too many young “masters.” Although many are content with where they are, others are unaware of how to move further. Still many others are exploring other arts not realizing much of what they seek is available closer to home. There is also a sizable group that would like more but is unwilling to give up what they think they have. Full cups don’t have much room. All that really matters however is continuing to educate oneself. Ed Parker always said, “The mind is like a parachute, it only works when it’s open.” If something is missing in your or your instructors Kenpo, ask intelligent questions.</p>
<p align="justify">  
A great deal of the SubLevel 4 information comes from my own lesson notes. Mr. Parker dictated the core and laid the foundation. He constantly scrutinized, examined, and decided what he personally wanted. This forced me to write my own Coursebooks for my students. The information was, and as far as I know, is not available in written form anywhere else. Mr. Parker expected me to keep track of, and codify what we were doing at the time. It allowed him the freedom to “think” freely, and removed the burden of organizing the information. He really disliked organizing his thoughts sometimes because it slowed him down in the creation process. He often asked or assigned students organizational problems. He formed a foundation for me that I will be utilizing perpetually.</p>
<p align="justify">         
In my lessons he stressed the execution of a sound workable Default Technique to strengthen and solidify a firm foundation and physical vocabulary. I was never allowed to deviate. Unlike Motion-Kenpo which is plagued by what I call the “what if syndrome,” Mr. Parker mandated I understand the importance of a specific sequential structure. This is the completely opposite of the “tailored” flexibility concept found in his general teachings. Although experimentation was a part of my lessons, he was the one that initiated it, until he was satisfied with the results. He often changed his directions, and I had to flow with the lesson of the day. He told me what to do, how to do it, and a little at a time, the “why.” The “why,” was most important, because he taught me “why” you couldn’t change techniques, not “why” you could. His lessons allowed Kenpo to be more destructive without maiming, as well as more passive if you desired. It does not attack the soft tissue of the eyes, throat or testicles because it doesn’t have to for effectiveness. If you remove soft tissue assaults in Motion-Kenpo, what do you have left? Nothing remains but the blunt force trauma available to any unskilled street fighter.</p>
<p align="justify">  
Lastly, Ed. Parker had a great working knowledge of manipulations. One of his goals was to insure the stability and execution of the self-defense technique against the “street grappler.” He emphasized “street” as opposed to strategies that might be employed in a competition venue. Anytime someone attacks you whether with a punch, kick or grab, the potential always exists for the situation to change to a grappling scenario.  </p>
<p align="justify">
Therefore as you execute a defense, your body must be moved in a manner to insure it can not only Survive the Initial Assault, but withstand and control the constant forward pressure of someone trying to encircle or grapple you whether high or low. It is important that you are able to do this within the sequential flow of the technique. This is another place where method and manner of execution en route to structural integrity makes this possible. The science of manipulations and ground fighting has been around for centuries, with many modern great experts (and personal friends of Parker) like the great Gene LeBell and Wally Jay. Ed Parker’s approach was to focus on the “how” of not going to the ground first, and groundwork second. After all Ed Parker was a black belt in jiu-jitsu of Okazaki influence.</p>
<p align="justify">  
In closing this segment, in comparison to Motion-Kenpo SL-4 is not initially flexible, although it does become so later. It is difficult for some who like to hypothesize to understand. It is closer to traditional Chinese methods than freeform. Even though there may be many “tailored” ways to perform Mr. Parker’s conceptual techniques, and even though those techniques are not wrong, they may not allow for a successful application of certain advanced principles. Ed Parker used to classify technique effectiveness on a scale of one through four. There is 1; ineffective, 2; effective, 3; more effective, and 4; most effective. SubLevel Four Kenpo is a natural 4. Techniques become less “abstract.” Kenpo techniques that have seemed ineffective or only marginally effective are, in fact, remarkably effective. In short, SubLevel Four Kenpo gives Mr. Parker the credit he truly deserves as you move from Motion-Kenpo Karate’s martial art, to SubLevel Four’s Combat Martial Science. </p>
<p align="right"><span class="top"><a href="/web/20111006004459/http://www.martialscienceuniversity.com/articles/">Return to Article Archive</a></span></p>
				</TD></TR>
				
<?php include 'footer.php' ?>