<?php
$pageTitle = 'Mad Kenpo Scientist pt. 2';
include 'header.php';
?>

<!--BEGIN CONTENT-->


			<TABLE WIDTH="100%" HEIGHT="100%" BORDER="0" CELLPADDING="3" CELLSPACING="5">
<!--PAGE NAME-->
				<TR><TD HEIGHT="25" BGCOLOR="#890C08" CLASS="BODY"><a name="top"></a>
				<a href="/web/20111230212544/http://www.martialscienceuniversity.com/" class="h1">
				<div>Excerpts from the Diary of a &quot;Mad&quot; Kenpo Scientist, Part Two<br><br></div></a></TD></TR>

<!--JUMP MENU-->
				<TR><TD BGCOLOR="#CCCCCC" class="BODY" VALIGN="TOP">
					<a href="/web/20111230212544/http://www.martialscienceuniversity.com/" class="art">
	<h1 align="center" class="art">The &quot;Kenpo-Karate&quot; &amp; JKD Connection</h1></a>
  <p align="center"><strong>By Ron Chap&eacute;l, Ph.D.</strong><br>
  (Published in Combat Martial Sports, March 02)</p>
<p align="right"><br>
  <a href="/web/20111230212544/http://www.martialscienceuniversity.com/articles/"><font size="1">Return to Article Archive</font></a></p>
<p align="justify">&nbsp;</p>
<p align="justify">Ed Parker’s creation, “Kenpo-Karate,” has a brother and a sister art. The “sister” is Jeet Kune Do (JKD). We’ll save the “brother” for another day. Kenpo-Karate and JKD are both training concepts, as opposed to styles, or even real systems of the martial arts. Although the Bruce Lee vehicle unlike the Ed Parker version was never designed to be commercial, Ed Parker had a considerable influenced in its creation and concept.</p>
<p align="justify">
Bruce Lee spoke extensively with him about his (Bruce’s) own personal goals and dissatisfaction with his Wing Chun training (even though he hadn’t really trained that long). He expressed a desire to learn as much as he could without the restraints imposed by any one discipline. Bruce became bored easily when he could not readily see benefit to what he was doing. Ed Parker argued this was pretty ambitious, but typical for a 22 year old. (I think we tend to forget Bruce was just a really talented kid.) Parker further expressed there must be variables to allow for the physical, emotional, and intellectual differences in students.   
For Bruce this was of little concern. He didn’t really care about students or teaching. Bruce Lee was on a personal mission to enhance his own skills and his salability to become a movie star. His teaching was primarily to insure he had training partners and of course, to learn from other accomplished martial artists to get to his personal goals. When Lee moved to Southern California his school was not open or known to the general public. The local “insiders” knew where it was, but to get in you had to bring something special to the table. It was located about five minutes away from Grandmaster Ark Wong’s School in the Los Angeles Chinatown.</p>
<p align="justify">
Ed Parker now realizing Lee was only interested in his own self-development, gave him some history making advice. Acknowledging Bruce’s obvious physical gifts, he suggested he should explore as much as possible from diverse teachers. Although Lee had already been doing this to a certain extent, Parker felt he should be introduced to the top guys, and of course Ed Parker knew them all. Bringing him together with notable martial artists like “Judo” Gene LeBell, Dan Inosanto and Sea Oh Choi to name a few, Ed Parker helped Bruce immensely with his martial arts. He advised Lee to study a variety of arts and take what he felt he could use. LeBell taught Bruce to grapple and became his stuntman in the “Green Hornet” TV show, while Choi was partially responsible for the awesome “Korean style” kicks Lee displayed on film. And of course, Dan Inosanto for teaching Bruce the many diverse weapons and for his Kenpo and Filipino Arts influence on Lee. Thus the seed to ultimately what became JKD was planted, but like motion based Kenpo-Karate, more a training concept than a style, and only a system within the confines of its own concept. His introduction by Ed Parker as well to William Self the director of the popular Batman T.V. series, who was casting for the Green Hornet, ultimately got him into television and jump-started his movie career.</p>
<p align="justify">   
Ed Parker’s approach for his Kenpo-Karate vehicle was somewhat different, but not as different as you might think. He felt instructors needed to be well rounded to be of the greatest benefit to all of their students. As a teacher, your personal strengths and weaknesses should not be visited on your students. You never know at what a student may excel, even though you as a teacher may not. Kenpo-Karate is designed to be of maximum benefit to the singular individual, and only personal effectiveness is the primary goal. It was simple and ingenious on the part of both these men.</p>
<p align="justify">  
Students and followers of both however, misunderstood. Kenpo-Karate practitioners continue to argue about the “right way” to execute a technique when there is none. They engage in “Hypothetical Kenpo” and intellectualize with no real foundation or basics, while conjuring up complicated “what if” scenarios. So-called JKD people argued about how to do JKD as well, while most of its original students don’t really teach it. What has emerged is “JKD Concepts” which is probably more appropriate considering its conceptual nature. Further JKD is closer to a “street style of sparring” and generally gives no solutions to self-defense grappling scenarios, much like Kenpo-Karate. Also unlike Kenpo-Karate, it doesn’t deal with modern street weapons, or surprise attacks.</p>
<p align="justify">  
That is not to say Bruce did not possess the knowledge or the ability to deal with these scenarios. To the contrary, much like Ed Parker, Bruce kept a lot to himself. Instead he chose to explore mostly the “street sparring” aspect with the majority of his student sparring partners. Most were not even aware Bruce could grapple, or had joint manipulation skills until he displayed them on film much later.</p>
<p align="justify">   
The most obvious JKD Kenpo-Karate connection can be seen in Kenpo-Karate’s “Freestyle Formulas.” These were derived from certain “Offensive Techniques” planned but never written for Ed Parker’s American Kenpo. Once again watered down and presented as formulas, they were to educate and prod the Kenpo-Karate student into “flexible thought” when it came to sparring and competition. By using the Kenpo-Karate concepts of Re-arrangement, Prefixing, Inserting, Addition, and Deletion, in conjunction with an established “base” formula and footwork, these Freestyle Formulas followed the same conceptual design as the rest of His Kenpo-Karate. I don’t think anyone ever had a better grasp of this component than Bob White, of Southern California, and his students. He has consistently proven this over the years in competition. There are “competitors,” and there are “fighters.” Bob White and his students are both.</p>
<p align="justify">  
Unfortunately however, most found this formulaic approach too complicated, and over the years, chose to ignore or abandon them altogether. Drafts of the last version of some the technique manuals Ed Parker was working on eliminated these formulas. Ed Parker created Kenpo-Karate to be conceptually and commercially viable out of necessity. He had to design it to be taught to the masses with maximum flexibility of thought and action. The “hard curriculum” he wanted to teach was not possible. Even though ultimately, it is only a small part of the whole of his “American Kenpo Knowledge,” Kenpo-Karate did have its own unique structure, and like JKD, only one expert.</p>
<p align="justify">  
First, Ed Parker created a guide he called the “Web of Knowledge.” This was a spiraling ascending chart consisting of the “theme” of the individual assaults in a progressive attack variable pattern. It was designed to insure students considered specific situations in their training process, and virtually dictated self-defense techniques and their order of presentation, and formed the basis for Kenpo-Karate’s lesson plan. Student/teachers focused on “techniques” when the Web of Knowledge is the truth base.  Although Parker insisted on individual flexibility on defense, he felt it was important to consider as many scenarios of attack as reasonably possible. Over time as the sociological climate changed, some of these scenarios have become outdated, while other new scenarios need to be considered.</p>
<p align="justify">
Revolutionary at the time, written “technique manuals” were created as a companion second part of the lesson plan. These were to give students a generalized starting point of ideas from which to extrapolate their defensive strategies dictated by the Web of Knowledge, based on concepts taught by Mr. Parker. No mention should be made of the earlier writings without acknowledging Tom Kelley and Richard Planas. These gentlemen contributed tremendously, and understand the philosophy of the material better than most for obvious reasons. They followed in the footsteps of Chuck Sullivan who was essentially there from the beginning, supporting as well as creating with Ed Parker.</p>
<p align="justify">   
Coming in personal contact with the majority of his students infrequently, the need of a different approach is what brought about Kenpo-Karate. So Ed Parker began teaching, not so much a system but this Kenpo-Karate Lesson Plan he intended students to use as a general guide. The Web of Knowledge in conjunction with emerging concepts was supposed to be the center, with the technique manuals to provide ideas for a starting point for personal interpretations. Remember the primary objective was for the individual to defend himself with the information provided as quickly as possible.</p>
<p align="justify">  
The problems here were many. For one Ed Parker was constantly evolving and growing. New ideas replaced old ones rapidly, usually too fast for his students. That leads us to the next problem. All of Kenpo-Karate’s instructors were also its students themselves. Most were converts from other arts who were attempting to learn Ed Parker’s ever-changing approach, and teach it at the same time. This in conjunction with the inherent flexibility of Kenpo-Karate, created mass confusion from school to school, instructor to instructor. What Ed Parker told one group in the morning, might be completely different from an afternoon session with a different audience.</p>
<p align="justify">  
Ed Parker knew the true sciences and more complex aspects of the whole of his “American Kenpo,” like traditional Chinese Arts, required very strictly taught basics and specific body mechanics to provide a solid long-term foundation. Additionally, even more specific continuing education under competent instruction would be absolutely necessary to move to true advanced levels. Like JKD, limited competent instructors hampered this. Like Bruce Lee, only Ed Parker was the expert of his art. He also knew it would be impossible to teach his American Kenpo as he envisioned it in the recesses of his mind.</p>
<p align="justify">  
Kenpo-Karate is essentially a motion-based approach designed as stated, to foster reasonable self-defense skills, in a relatively short period of time. To this end, Kenpo-Karate routinely attacks soft human tissue such as the throat, testicles, and eyes to insure effectiveness. It teaches the student to overwhelm an opponent with multiple rapid fire flailing strikes and kicks. Conceptually simple, but it can be extremely effective in striking situations against the unskilled. It is very ineffective however in “hands on” or “grappling” circumstances because of the absence of other knowledge. This is the reason many practitioners have decided to augment their skills with grappling disciplines. Most instructors in Kenpo-Karate teach students to turn “grabbing attacks” into “attempted grab attacks.” Once grabbed, hugged, choked etc. they are hard pressed to teach students how to extricate themselves. In essence Kenpo-Karate is a more sophisticated approach to many self-defense courses successfully taught in schools and colleges throughout the country. This is pure marketing genius on the part of Ed Parker.</p>
<p align="justify">  
As a limited layperson striking art however, this is where the genius of the man really showed. Because this creation is based on an “Alphabetical and Numerical Re-arrangement Concept,” its variations are literally infinite. Therefore a student may study this Kenpo-Karate facet of American Kenpo on a superficial level, or if he/she chooses, explore its interpretations of motion endlessly into old age. This version is known for its “journey” approach, and is the method Parker chose to proliferate. It is extremely flexible and promotes personal development and style over and above structure. Kenpo-Karate is about 10% structure, and 90% personal interpretation. Ed Parker’s American Kenpo is actually the reverse, and more like the traditional Chinese disciplines, with 90% very rigid structure, and 10% of tailored flexibility in the beginning.</p>
<p align="justify"> 
The reason is simple. Kenpo-Karate is completely dominated by what Ed Parker called the Re-arrangement and Tailoring Concepts of motion. This is its strength and its weakness. Remember Ed Parker said, “Tailored by self means limited by self.” He also adopted a saying from science. “General knowledge always produces general results.” Although Kenpo-Karate may be studied infinitely, and produce very positive results, there is specific knowledge not found within its structure. No matter how long you re-arrange and explore its movements and structure, this knowledge cannot be found. Consider this reality. There is no physical or mental discipline in existence, where you may extrapolate the higher echelons by re-arranging it, or tailoring it to your own personal preferences.</p>
<p align="justify">  
Your base of knowledge must be very specific and well defined before you attempt to build on it and move upward. You cannot do this with generalities. You cannot build a skyscraper’s first floor to your own whims. The foundation has to be rock solid and the physics of building construction will dictate its architecture in a manner you may not personally like. Kenpo-Karate’s popularity in part, comes from the lack of strict structure found in other arts, as well as its relatively rapid progress through its ranks. But the trade off is a hard foundation that is needed to sustain and create the base for more advanced development and internal energy. This is the reason why there are so many young “masters” of Kenpo-Karate. All that is really required is you “master” your own circumstances with regard to its structure.</p>
<p align="justify">  
As an entity it has no real scientific principles and is virtually conceptually driven. At its best it is a “pseudo-science,” and according to Ed Parker himself, created by a process called “Comparative Analysis.” The so-called “principles” are actually simple rules whose validity is constrained by its conceptual context. The “rules” may be absolute, but only as they pertain to the individual using it at the time. That is, “Your rule may not be mine if it doesn’t work for me, no matter how well it works for you.” Students are encouraged to “find another way to make it work,” over and above “continuing to work on the move for years.”  
Loyal practitioners truly want to believe it’s hard science, but it isn’t. It does however borrow ideas from science. But even then, very little is transportable to this conceptual vehicle. What some may call principles, outside of the context of Kenpo-Karate would have no meaning. The thought you could train in something for a few years, performing a group of techniques tailored to your personal preferences, and then take your experience and work your way to mastership is totally illogical. You may get to higher levels, but only within the constraints of the limited concept. There are masters of Kenpo-Karate, but that doesn’t mean they are masters of other aspects or higher levels of Ed Parker’s American Kenpo.</p>
<p align="justify">  
Intelligent teachers and practitioners have realized something is missing from Kenpo-Karate. Many like Bob White years ago, borrowed the sport concept of cross training. Some are flocking in large numbers to grappling and manipulation disciplines. Others are quietly talking about the techniques they wouldn’t use or the ones that “don’t work.” Others still, are really struggling to make sense of what they have been told and taught by teachers with a limited effective curriculum.</p>
<p align="justify">  
Although the idea of seeking knowledge from any source is commendable, some have even sought acupuncture charts in an attempt to “reverse engineer” techniques, and gain knowledge of nerve locations in combat scenarios. They are unaware of how much knowledge is missing and cannot be found in that methodology. Kenpo-Karate doesn’t provide the structure for such a process. Also acupuncture charts are much like Ed Parker’s technique Manuals. They are a guide, and are not gospel. Especially when used in an active martial environment.</p>
<p align="justify">  
Others simply point the finger at the obvious deficiencies and abandon Kenpo-Karate altogether. This is much easier than looking inward and seeing the same deficient circumstances in oneself or ones teacher. You’ll find ex-Kenpo students in abundance in Russian, Filipino, and other eclectic arts. Some don’t mind being a beginner somewhere else as long as they keep their ranks in Kenpo. I have always found it curious that many speak as if what they know is all Ed Parker knew. They routinely suggest they pretty much “know” the material, and now are on the Bruce Lee journey sampling other arts. They do not seem to leave room for the possibility that Ed Parker like Bruce Lee was ahead of his students, and might have known things he didn’t teach them.  
One of the things that kept Mr. Parker held in such high esteem was what students felt of his physical skill. No one seemed capable of physically duplicating what he did. Not understanding many thought the answer was simply to hit harder. As an example, many elements from the Chinese Sciences like the pak-sao, or “slapping checks” are evident in all of even his early movements recorded on film and tape. Yet, he never taught or wrote about them. Some have attempted to mimic him; not realizing “slapping” yourself in the wrong place at the wrong time can have devastating consequences in real combat. Other have simply followed the technique manuals and used Ed Parker’s written substitute, “positional check.”</p>
<p align="justify"> 
He also made extensive use of nerve strikes and pressure points in all he did, but never talked about these things either after including nerve charts in his first book on Kenpo in 1961. He often told a story he called “The Menu of Death” that illustrated he had a knowledge of these things. Interestingly students laughed at the punch line but no one ever asked him the implications of the story. Still others attempted to duplicate Ed Parker’s awesome abilities by concentrating on speed, hitting students extremely hard to get the desired effect. Although effective, it is Neanderthal in comparison.</p>
<p align="justify">  
Students of American Kenpo have to ask themselves if Ed Parker’s “Infinite Insights” books truly represents the sum of his knowledge as some off-shoot Kenpoists have claimed. Ed Parker himself stated in the second volume of that series, that the material therein was from the early seventies, and it took him to the eighties to organize it. I have video of Ed Parker doing all of the techniques from the late sixties and early seventies, and they are essentially unchanged from what most are doing in a new millennium, over forty years later. Curious since that is not what Ed Parker was doing, or how he moved at the time he passed in 1990. “Traditional Kenpo” which many claim to perpetuate, by Mr. Parker’s own standards is an oxymoron. There is no such thing, just those who have stopped learning and educating themselves.</p>
<p align="right"><span class="top"><a href="/web/20111230212544/http://www.martialscienceuniversity.com/articles/">Return to Article Archive</a></span></p>
				</TD></TR>
				
<?php include 'footer.php' ?>